<?php

namespace Wucdbm\Manticore\ConfigFactory\Config\Manticore;

readonly class SearchdConfig extends AbstractCoreConfig
{
    public function __construct(array $config)
    {
        parent::__construct('searchd', $config);
    }

    /**
     * @return string[]
     */
    protected function getConfigReference(): array
    {
        return [
            'access_plain_attrs' => 'https://manual.manticoresearch.com/Server_settings/Searchd#access_plain_attrs',
            'access_blob_attrs' => 'https://manual.manticoresearch.com/Server_settings/Searchd#access_blob_attrs',
            'access_doclists' => 'https://manual.manticoresearch.com/Server_settings/Searchd#access_doclists',
            'access_hitlists' => 'https://manual.manticoresearch.com/Server_settings/Searchd#access_hitlists',
            'access_dict' => 'https://manual.manticoresearch.com/Server_settings/Searchd#access_dict',
            'agent_connect_timeout' => 'https://manual.manticoresearch.com/Server_settings/Searchd#agent_connect_timeout',
            'agent_query_timeout' => 'https://manual.manticoresearch.com/Server_settings/Searchd#agent_query_timeout',
            'agent_retry_count' => 'https://manual.manticoresearch.com/Server_settings/Searchd#agent_retry_count',
            'agent_retry_delay' => 'https://manual.manticoresearch.com/Server_settings/Searchd#agent_retry_delay',
            'attr_flush_period' => 'https://manual.manticoresearch.com/Server_settings/Searchd#attr_flush_period',
            'auto_optimize' => 'https://manual.manticoresearch.com/Server_settings/Searchd#auto_optimize',
            'parallel_chunk_merges' => 'https://manual.manticoresearch.com/Server_settings/Searchd#parallel_chunk_merges',
            'merge_chunks_per_job' => 'https://manual.manticoresearch.com/Server_settings/Searchd#merge_chunks_per_job',
            'auto_schema' => 'https://manual.manticoresearch.com/Server_settings/Searchd#auto_schema',
            'binlog_flush' => 'https://manual.manticoresearch.com/Server_settings/Searchd#binlog_flush',
            'binlog_common' => 'https://manual.manticoresearch.com/Server_settings/Searchd#binlog_common',
            'binlog_max_log_size' => 'https://manual.manticoresearch.com/Server_settings/Searchd#binlog_max_log_size',
            'binlog_path' => 'https://manual.manticoresearch.com/Server_settings/Searchd#binlog_path',
            'boolean_simplify' => 'https://manual.manticoresearch.com/Server_settings/Searchd#boolean_simplify',
            'buddy_path' => 'https://manual.manticoresearch.com/Server_settings/Searchd#buddy_path',
            'client_timeout' => 'https://manual.manticoresearch.com/Server_settings/Searchd#client_timeout',
            'collation_libc_locale' => 'https://manual.manticoresearch.com/Server_settings/Searchd#collation_libc_locale',
            'collation_server' => 'https://manual.manticoresearch.com/Server_settings/Searchd#collation_server',
            'data_dir' => 'https://manual.manticoresearch.com/Server_settings/Searchd#data_dir',
            'attr_autoconv_strict' => 'https://manual.manticoresearch.com/Server_settings/Searchd#attr_autoconv_strict',
            'diskchunk_flush_search_timeout' => 'https://manual.manticoresearch.com/Server_settings/Searchd#diskchunk_flush_search_timeout',
            'diskchunk_flush_write_timeout' => 'https://manual.manticoresearch.com/Server_settings/Searchd#diskchunk_flush_write_timeout',
            'docstore_cache_size' => 'https://manual.manticoresearch.com/Server_settings/Searchd#docstore_cache_size',
            'engine' => 'https://manual.manticoresearch.com/Server_settings/Searchd#engine',
            'expansion_limit' => 'https://manual.manticoresearch.com/Server_settings/Searchd#expansion_limit',
            'expansion_merge_threshold_docs' => 'https://manual.manticoresearch.com/Server_settings/Searchd#expansion_merge_threshold_docs',
            'expansion_merge_threshold_hits' => 'https://manual.manticoresearch.com/Server_settings/Searchd#expansion_merge_threshold_hits',
            'expansion_phrase_limit' => 'https://manual.manticoresearch.com/Server_settings/Searchd#expansion_phrase_limit',
            'expansion_phrase_warning' => 'https://manual.manticoresearch.com/Server_settings/Searchd#expansion_phrase_warning',
            'grouping_in_utc' => 'https://manual.manticoresearch.com/Server_settings/Searchd#grouping_in_utc',
            'timezone' => 'https://manual.manticoresearch.com/Server_settings/Searchd#timezone',
            'ha_period_karma' => 'https://manual.manticoresearch.com/Server_settings/Searchd#ha_period_karma',
            'ha_ping_interval' => 'https://manual.manticoresearch.com/Server_settings/Searchd#ha_ping_interval',
            'hostname_lookup' => 'https://manual.manticoresearch.com/Server_settings/Searchd#hostname_lookup',
            'jobs_queue_size' => 'https://manual.manticoresearch.com/Server_settings/Searchd#jobs_queue_size',
            'join_batch_size' => 'https://manual.manticoresearch.com/Server_settings/Searchd#join_batch_size',
            'join_cache_size' => 'https://manual.manticoresearch.com/Server_settings/Searchd#join_cache_size',
            'listen_backlog' => 'https://manual.manticoresearch.com/Server_settings/Searchd#listen_backlog',
            'kibana_version_string' => 'https://manual.manticoresearch.com/Server_settings/Searchd#kibana_version_string',
            'listen' => 'https://manual.manticoresearch.com/Server_settings/Searchd#listen',
            'listen_tfo' => 'https://manual.manticoresearch.com/Server_settings/Searchd#listen_tfo',
            'log' => 'https://manual.manticoresearch.com/Server_settings/Searchd#log',
            'max_batch_queries' => 'https://manual.manticoresearch.com/Server_settings/Searchd#max_batch_queries',
            'max_connections' => 'https://manual.manticoresearch.com/Server_settings/Searchd#max_connections',
            'max_threads_per_query' => 'https://manual.manticoresearch.com/Server_settings/Searchd#max_threads_per_query',
            'max_filters' => 'https://manual.manticoresearch.com/Server_settings/Searchd#max_filters',
            'max_filter_values' => 'https://manual.manticoresearch.com/Server_settings/Searchd#max_filter_values',
            'max_open_files' => 'https://manual.manticoresearch.com/Server_settings/Searchd#max_open_files',
            'max_packet_size' => 'https://manual.manticoresearch.com/Server_settings/Searchd#max_packet_size',
            'mysql_version_string' => 'https://manual.manticoresearch.com/Server_settings/Searchd#mysql_version_string',
            'net_workers' => 'https://manual.manticoresearch.com/Server_settings/Searchd#net_workers',
            'net_wait_tm' => 'https://manual.manticoresearch.com/Server_settings/Searchd#net_wait_tm',
            'net_throttle_accept' => 'https://manual.manticoresearch.com/Server_settings/Searchd#net_throttle_accept',
            'net_throttle_action' => 'https://manual.manticoresearch.com/Server_settings/Searchd#net_throttle_action',
            'network_timeout' => 'https://manual.manticoresearch.com/Server_settings/Searchd#network_timeout',
            'node_address' => 'https://manual.manticoresearch.com/Server_settings/Searchd#node_address',
            'not_terms_only_allowed' => 'https://manual.manticoresearch.com/Server_settings/Searchd#not_terms_only_allowed',
            'optimize_cutoff' => 'https://manual.manticoresearch.com/Server_settings/Searchd#optimize_cutoff',
            'persistent_connections_limit' => 'https://manual.manticoresearch.com/Server_settings/Searchd#persistent_connections_limit',
            'pid_file' => 'https://manual.manticoresearch.com/Server_settings/Searchd#pid_file',
            'preopen_tables' => 'https://manual.manticoresearch.com/Server_settings/Searchd#preopen_tables',
            'pseudo_sharding' => 'https://manual.manticoresearch.com/Server_settings/Searchd#pseudo_sharding',
            'replication_connect_timeout' => 'https://manual.manticoresearch.com/Server_settings/Searchd#replication_connect_timeout',
            'replication_query_timeout' => 'https://manual.manticoresearch.com/Server_settings/Searchd#replication_query_timeout',
            'replication_retry_count' => 'https://manual.manticoresearch.com/Server_settings/Searchd#replication_retry_count',
            'replication_retry_delay' => 'https://manual.manticoresearch.com/Server_settings/Searchd#replication_retry_delay',
            'qcache_max_bytes' => 'https://manual.manticoresearch.com/Server_settings/Searchd#qcache_max_bytes',
            'qcache_thresh_msec' => 'https://manual.manticoresearch.com/Server_settings/Searchd#qcache_thresh_msec',
            'qcache_ttl_sec' => 'https://manual.manticoresearch.com/Server_settings/Searchd#qcache_ttl_sec',
            'query_log_format' => 'https://manual.manticoresearch.com/Server_settings/Searchd#query_log_format',
            'query_log_min_msec' => 'https://manual.manticoresearch.com/Server_settings/Searchd#query_log_min_msec',
            'query_log' => 'https://manual.manticoresearch.com/Server_settings/Searchd#query_log',
            'query_log_mode' => 'https://manual.manticoresearch.com/Server_settings/Searchd#query_log_mode',
            'read_buffer_docs' => 'https://manual.manticoresearch.com/Server_settings/Searchd#read_buffer_docs',
            'read_buffer_hits' => 'https://manual.manticoresearch.com/Server_settings/Searchd#read_buffer_hits',
            'read_unhinted' => 'https://manual.manticoresearch.com/Server_settings/Searchd#read_unhinted',
            'reset_network_timeout_on_packet' => 'https://manual.manticoresearch.com/Server_settings/Searchd#reset_network_timeout_on_packet',
            'rt_flush_period' => 'https://manual.manticoresearch.com/Server_settings/Searchd#rt_flush_period',
            'rt_merge_iops' => 'https://manual.manticoresearch.com/Server_settings/Searchd#rt_merge_iops',
            'rt_merge_maxiosize' => 'https://manual.manticoresearch.com/Server_settings/Searchd#rt_merge_maxiosize',
            'seamless_rotate' => 'https://manual.manticoresearch.com/Server_settings/Searchd#seamless_rotate',
            'secondary_index_block_cache' => 'https://manual.manticoresearch.com/Server_settings/Searchd#secondary_index_block_cache',
            'secondary_indexes' => 'https://manual.manticoresearch.com/Server_settings/Searchd#secondary_indexes',
            'server_id' => 'https://manual.manticoresearch.com/Server_settings/Searchd#server_id',
            'shutdown_timeout' => 'https://manual.manticoresearch.com/Server_settings/Searchd#shutdown_timeout',
            'shutdown_token' => 'https://manual.manticoresearch.com/Server_settings/Searchd#shutdown_token',
            'skiplist_cache_size' => 'https://manual.manticoresearch.com/Server_settings/Searchd#skiplist_cache_size',
            'snippets_file_prefix' => 'https://manual.manticoresearch.com/Server_settings/Searchd#snippets_file_prefix',
            'sphinxql_state' => 'https://manual.manticoresearch.com/Server_settings/Searchd#sphinxql_state',
            'sphinxql_timeout' => 'https://manual.manticoresearch.com/Server_settings/Searchd#sphinxql_timeout',
            'ssl_ca' => 'https://manual.manticoresearch.com/Server_settings/Searchd#ssl_ca',
            'ssl_cert' => 'https://manual.manticoresearch.com/Server_settings/Searchd#ssl_cert',
            'ssl_key' => 'https://manual.manticoresearch.com/Server_settings/Searchd#ssl_key',
            'subtree_docs_cache' => 'https://manual.manticoresearch.com/Server_settings/Searchd#subtree_docs_cache',
            'subtree_hits_cache' => 'https://manual.manticoresearch.com/Server_settings/Searchd#subtree_hits_cache',
            'threads' => 'https://manual.manticoresearch.com/Server_settings/Searchd#threads',
            'thread_stack' => 'https://manual.manticoresearch.com/Server_settings/Searchd#thread_stack',
            'unlink_old' => 'https://manual.manticoresearch.com/Server_settings/Searchd#unlink_old',
            'watchdog' => 'https://manual.manticoresearch.com/Server_settings/Searchd#watchdog',
        ];
    }
}
